# Generated by Django 6.0.5 on 2026-05-12 17:35

import api.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='year',
            field=models.SmallIntegerField(validators=[api.validators.validate_year], verbose_name='Год'),
        ),
    ]
